name: updatium
description: Get Android app updates straight from the source.
publish_to: 'none'

version: 1.2.9+2325

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # --- Localization (PO Support) ---
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.0
  
  # --- UI & Icons ---
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  flex_color_picker: ^3.7.1
  animations: ^2.0.11
  fluttertoast: ^9.0.0
  flutter_typeahead: ^5.2.0
  flutter_markdown: ^0.7.7+1
  markdown: ^7.3.0
  flex_seed_scheme: ^3.5.0 # Required for some dynamic color features

  # --- State & Storage ---
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  crypto: ^3.0.6
  bcrypt: ^1.1.3

  # --- System & Device ---
  device_info_plus: ^12.1.0
  connectivity_plus: ^7.0.0
  battery_plus: ^7.0.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  share_plus: ^12.0.0
  file_picker: ^10.1.9
  app_links: ^6.4.0
  android_intent_plus: ^6.0.0
  http: ^1.4.0

  # --- Background & Tasks ---
  background_fetch: ^1.3.8
  flutter_foreground_task: ^9.1.0
  flutter_local_notifications: ^18.0.1
  flutter_fgbg: ^0.7.1

  # --- Specialized Packages ---
  webview_flutter: ^4.13.0
  html: ^0.15.6
  flutter_archive: ^6.0.3
  flutter_charset_detector: ^5.0.0
  hsluv: ^1.1.3
  equations: ^5.0.2

  # --- Git Dependencies ---
  android_package_installer:
    git:
      url: https://github.com/playbott/android_package_installer
      ref: main
  android_package_manager:
    git:
      url: https://github.com/ImranR98/android_package_manager
      ref: master
  shared_storage:
    git:
      url: https://github.com/AlexBacich/shared-storage
      ref: master
  android_system_font:
    git:
      url: https://github.com/re7gog/android_system_font
      ref: master
  shizuku_apk_installer:
    git:
      url: https://github.com/wilver06w/shizuku_apk_installer
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/graphics/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/graphics/
    - assets/ca/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
